image: php:7.4.9
pipelines:
  branches:
    master:
      - step:
          name: Install OS dependencies, run PHPUnit, create BUILD
          script:
            - apt-get update && apt-get install -y unzip git libxml2-dev zlib1g-dev libzip-dev zip
            - docker-php-ext-install soap
            - docker-php-ext-install zip
            - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
            - composer install
            - composer install --no-dev -o
            - zip -r build.zip . -x *.git* *tests* *vagrant*
          artifacts:
            - build.zip
            - deploy.sh
      - step:
          name: Deploy build with SCP to PRODUCTION
          script:
            - pipe: atlassian/scp-deploy:0.3.11
              variables:
                USER: $USER
                SERVER: $SERVER
                REMOTE_PATH: '/var/builds/$BUILD_PATH/build-$BITBUCKET_COMMIT.zip'
                LOCAL_PATH: 'build.zip'
      - step:
          name: Install deploy.sh artifact
          script:
            - pipe: atlassian/scp-deploy:0.3.11
              variables:
                USER: $USER
                SERVER: $SERVER
                REMOTE_PATH: '/usr/local/bin/deploy.sh'
                LOCAL_PATH: 'deploy.sh'
      - step:
          name: Set permissions for deploy.sh
          script:
            - pipe: atlassian/ssh-run:0.2.5
              variables:
                SSH_USER: $USER
                SERVER: $SERVER
                COMMAND: 'chmod +x /usr/local/bin/deploy.sh'
      - step:
          name: Move current app to OLD and replace with new BUILD ZIP
          script:
            - pipe: atlassian/ssh-run:0.2.5
              variables:
                SSH_USER: $USER
                SERVER: $SERVER
                COMMAND: 'deploy.sh build-$BITBUCKET_COMMIT build-$BITBUCKET_COMMIT.zip $BUILD_PATH $BITBUCKET_BRANCH'