version: '3.2'

services:

  frontend:
    build: frontend
    ports:
      - 30000:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app

  api:
    build: api
    ports:
      - 30001:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app

  shopify:
    build: shopify
    ports:
      - 30004:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: cgsmpoim_shipwise
      MYSQL_USER: app
      MYSQL_PASSWORD: 123
    ports:
      - "30002:3306"
    volumes:
      - ./mysql-data/var/lib/mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '30003:80'
    environment:
      PMA_HOST: mysql
      PMA_USER: app
      PMA_PASSWORD: 123
      PMA_ARBITRARY: 1
    depends_on:
      - mysql
