version: '3.2'

services:

  frontend:
    build: frontend
    environment:
      COMPOSER_HOME: /opt/composer
      PHP_ENABLE_XDEBUG: 1
    volumes:
      # Mount source-code for development
      - ./:/app

  api:
    build: api
    environment:
      COMPOSER_HOME: /opt/composer
      PHP_ENABLE_XDEBUG: 1
    volumes:
      # Mount source-code for development
      - ./:/app

  mysql:
    image: mysql:8
    entrypoint: ['docker-entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: cgsmpoim_shipwise
      MYSQL_USER: app
      MYSQL_PASSWORD: 123
    volumes:
      - ./mysql-data/var/lib/mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: app
      PMA_PASSWORD: 123
      PMA_ARBITRARY: 1
    depends_on:
      - mysql
