<?php

namespace frontend\models\forms;

use api\modules\v1\models\shipping\ShipmentRateEx;
use common\models\Integration;
use common\models\IntegrationMeta;

class IntegrationForm extends \yii\base\Model
{

    public Integration $integration;

    /** @var array $metaData IntegrationMeta array */
    public array $metaData;

    public function init()
    {
        $this->integration = new Integration();
        $this->metaData[] = new IntegrationMeta();
        parent::init(); // TODO: Change the autogenerated stub
    }



    public function rules()
    {
        return [
            [['integration', 'metaData'], 'required'],
        ];
    }

    public function save()
    {
        $transaction = \Yii::$app->db->beginTransaction();

        if (!$this->integration->save()) {
            $transaction->rollBack();
            return false;
        }


        /**  @var $metaDatum IntegrationMeta */
        foreach ($this->metaData as $metaDatum) {
            $metaDatum->integration_id = $this->integration->id;
            if (!$metaDatum->save()) {
                $transaction->rollBack();
                return false;
            }

        }
        $transaction->commit();
        return true;
    }

}