<?php


namespace common\components;


use common\models\Order;

class FulfillmentService extends \yii\base\Component
{
    const EVENT_BEFORE_FULFILLMENT_SEND = 'fulfillmentSend';
    const EVENT_AFTER_FULFILLMENT_CREATE = 'fulfillmentCreate';
    const EVENT_FULFILLMENT_ERROR = 'fulfillmentError';

    public $api;

    public function init()
    {

        parent::init(); // TODO: Change the autogenerated stub
    }

    public function createOrder(Order $order)
    {
        $this->trigger(self::EVENT_BEFORE_FULFILLMENT_SEND);

        /**
         * PackagingRules
         *
         * id, order, trigger, event, rules, csusotmer_id carp
         *      1     EVENT_BEFORE_FULFLILEMNT,  DateCheckBehavior
         *      2     BEFORE, ZipCodeLookupBehavior
         */

        try {
            $this->api->send($order);
            $this->trigger(self::EVENT_AFTER_FULFILLMENT_CREATE);
        } catch (\Exception $e) {
            $this->trigger(self::EVENT_FULFILLMENT_ERROR);
        }
    }

    public function fetchTracking(Order $order)
    {
    }
}