<?php

namespace common\models;

class ScheduledOrder extends \yii\db\ActiveRecord
{
    public function beforeSave($insert)
    {
        if ($insert) {
            $priorOrderIds = ScheduledOrder::find()->where(['order_id' => $this->order_id])->all();
            foreach ($priorOrderIds as $priorOrderId) {
                $priorOrderId->delete();
            }
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'scheduled_orders';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['order_id', 'status_id', 'customer_id', 'scheduled_date'], 'required'],
            [['order_id', 'status_id'], 'integer'],
        ];
    }

    /**
     * Relation for order
     *
     * @return \yii\db\ActiveQuery
     */
    public function getOrder()
    {
        return $this->hasOne(Order::class, ['id' => 'order_id']);
    }

    /**
     * Relation for status
     *
     * @return \yii\db\ActiveQuery
     */
    public function getStatus()
    {
        return $this->hasOne(Status::class, ['id' => 'status_id']);
    }

    /**
     * Relation for status
     *
     * @return \yii\db\ActiveQuery
     */
    public function getCustomer()
    {
        return $this->hasOne(Customer::class, ['id' => 'customer_id']);
    }
}