<?php

namespace frontend\models;


use Stripe\SetupIntent;
use Stripe\Stripe;
use Yii;

/**
 * This is the model class for table "payment-method".
 *
 */
class PaymentMethod extends \common\models\PaymentMethod
{
    /** @var string Used for stripe form */
    public $card_number;
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $this->setAttribute('customer_id', Yii::$app->user->identity->getCustomerId());
        $this->setupIntent = SetupIntent::create([
            'customer' => Yii::$app->user->identity->getCustomerStripeId(),
        ]);


    }
}
