name: PHP CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Prepare docker
      run: make docker-compose.override.yml

    - name: Set up Docker Compose
      uses: docker/compose-action@1.2.0
      with:
        compose-file: docker-compose.yaml

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Setup config files
      run: make api/web/index.php

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: make vendor/autoload.php

    - name: Run Codeception tests
      run: make test
